"""
Common functions and classes to support command line processing.
"""
import argparse
from typing import NamedTuple, Optional, Any


class Function(NamedTuple):
    """
    A :class:`typing.NamedTuple` that stores information for :mod:`argparse` to process command line arguments.
    Each :class:`Function` maps to a single command line argument. These make up the base command line API.
    """
    name: str
    """The name of the command line function. This is used as the second argument on the command line."""

    help: str
    """Some help text for the ``--help`` option :mod:`argparse` uses. This help described what the function does."""

    args: Optional[list[tuple[str, str]]] = None
    """An optional list of arguments and associated help text for the given command line function. The arguments
    given here will be checked by argparse and an error raised if they are note supplied."""


class Component(NamedTuple):
    """
    A :class:`typing.NamedTuple` that stores information for :mod:`argparse`. Each Component houses multiple
    command line :class:`Function` s and represents the logical grouping of functions as found in the
    `Interactive Brokers documentation <https://www1.interactivebrokers.com/api/doc.html>`_ .

    Each of the Components resolves into a command line function grouping e.g. ib-marketdata/ib-marketdata.exe. These
    contain their own titles, descriptions and help files when examining the help files generated by :mod:`argparse` .
    """
    title: str
    """The title of the grouping."""

    description: str
    """A description of what the grouping does."""

    help: str
    """A help file for use by :mod:`argparse` ``--help`` option."""

    functions: list[Function]
    """A list of :class:`Function` s that make up the grouping. These represent the actual command line functions
    that are called. A :class:`Component` by itself does nothing."""


def parse_arguments(
        group: str,
        description: str,
        help: str,
        component_functions: dict[str, list[Function]]
) -> argparse.Namespace:
    """
    The main function for parsing command line arguments. It takes arguments that are used to build a :class:`Component`
    for use by :mod:`argparse`.

    :param str group: The title of the command line grouping.
    :param str description: What the grouping aims to do in general.
    :param str help: A help file for use with :mod:`argparse` .
    :param dict[str, list[Function]] component_functions: A dictionary mapping the group name to a list of its
                                                          constituent :class:`Function` s. For speed we pass a
                                                          dictionary that just has the component functions for the
                                                          group, though we can use a dictionary that contains all
                                                          component functions.
    :rtype: argparse.Namespace
    :return: Namespace of parsed command line arguments.
    """

    # Get the component functions for the particular group.
    functions: list[Function] = component_functions[group]

    # Create a Component to represent all the group's information for argparse.
    component: Component = Component(
        title=group,
        description=description,
        help=help,
        functions=functions
    )

    # Generate an instance of the argument parser for use with current command line.
    parser: argparse.ArgumentParser = argparse.ArgumentParser()

    # Create a subparser to handle the component functions.
    subparsers: Any = parser.add_subparsers(
        title=component.title,
        description=component.description,
        help=component.help
    )

    # For each component function
    for func in component.functions:
        # Add the function to the subparsers, with help text for argparse.
        func_parser: Any = subparsers.add_parser(
            func.name,
            help=func.help
        )

        # If the function had arguments
        if func.args is not None:
            # For each argument
            for arg in func.args:
                # Add the argument to the function parser, with help text.
                func_parser.add_argument(
                    arg[0],
                    help=arg[1]
                )

    # Parse the arguments and return a namespace of the parsed arguments.
    return parser.parse_args()
